name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@daa73cf39de99d47b500df80fbe6cad5abdf434b
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      references-internal-git-repo: true

# If using a git submodule, add 
#      pull-git-submodules: true
